trigger:
- none

variables:
  buildid: '$(Build.BuildNumber)'


schedules:
- cron: "10 00 * * 2-6"  # Run the task every day at 7PM CST
  branches:
    include:
    - S2P-Automation-Demo
  always: true


pool:
  vmImage: 'ubuntu-latest'

steps:
    - task: UsePythonVersion@0
      inputs:
       versionSpec: '3.9'
       addToPath: true         
      
    - script:
       python -m pip install --upgrade.pip
       pip install selenium
       pip install behave

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          behave features/Login.feature 
          
          

