trigger:
- none

variables:
  buildid: '$(Build.BuildNumber)'


schedules:
- cron: "10 00 * * 2-6"  # Run the task every day at 7PM CST
  branches:
    include:
    - S2P-Automation-Demo
  always: true


pool:
  vmImage: 'ubuntu-latest'

steps:
    - task: UsePythonVersion@0
      inputs:
       versionSpec: '3.9'
       addToPath: true         
      
    - script:
       pip install selenium
       pip install pytest
       pip install -r requirements.txt
       pip install openpyxl
       pip install pynput
       pip install -e .
       pip install allure-pytest



    - script:
       pytest -v -s --alluredir="./allure-results/" ./testCases/CI/Sanity/test_TC02_VerifyE2EFunctionalityForPODocumentType.py
       allure generate allure-results
       cd allure-results && ls && pwd
       cd ../allure-report && ls

      inputs:
          reportDir: 'allure-report'



   
        
       
          
          

